In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/uciml/sms-spam-collection-dataset/spam.csv

In [2]:
df = pd.read_csv("/kaggle/input/datasets/uciml/sms-spam-collection-dataset/spam.csv",encoding="latin-1")
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [3]:
uq = set(df["v2"].str.lower().str.findall(r"\b\w+\b").explode().dropna())

In [4]:
val,cnt = np.unique(df["v2"].str.lower().str.findall(r"\b\w+\b").explode().dropna(), return_counts=True)
val,cnt

(array(['0', '00', '000', ..., 'ûïharry', 'ûò', 'ûówell'], dtype=object),
 array([ 4, 10, 29, ...,  1,  9,  1]))

In [5]:
vals,cnts = np.unique(df.loc[df["v1"]=="spam", "v2"].str.lower().str.findall(r"\b\w+\b").explode().dropna(), return_counts=True)
vals,cnts

(array(['0', '00', '000', ..., 'ûªve', 'ûï', 'ûïharry'], dtype=object),
 array([ 4, 10, 29, ...,  1,  1,  1]))

In [6]:
p = pd.DataFrame({"val":vals, "cnt":cnts})
p["cnt"] = p["cnt"]/ sum(p["cnt"])
p

               val       cnt
0                0  0.000207
1               00  0.000518
2              000  0.001503
3     008704050406  0.000104
4             0089  0.000052
...            ...       ...
2896          åòit  0.000052
2897           ì¼1  0.000052
2898          ûªve  0.000052
2899            ûï  0.000052
2900       ûïharry  0.000052

[2901 rows x 2 columns]